name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: "3.3.4"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.0.0
  http: ^1.2.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
