// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_n8JGmiYI6Llx6tR0qDn_iJ6vY_I5PX8',
    appId: '1:549694778093:web:a3e37d5e4dd5d63e15fae4',
    messagingSenderId: '549694778093',
    projectId: 'flash-chat-abde3',
    authDomain: 'flash-chat-abde3.firebaseapp.com',
    storageBucket: 'flash-chat-abde3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIkJOjRuk2hb5MMsmHvrhR9fKf0r9zsE',
    appId: '1:549694778093:android:616e39ce9586c53915fae4',
    messagingSenderId: '549694778093',
    projectId: 'flash-chat-abde3',
    storageBucket: 'flash-chat-abde3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7bMyz1UWQwtnNf_WIer12y7KNOlAjPs',
    appId: '1:549694778093:ios:56f67fb3cb460ea615fae4',
    messagingSenderId: '549694778093',
    projectId: 'flash-chat-abde3',
    storageBucket: 'flash-chat-abde3.appspot.com',
    iosBundleId: 'co.emanueledelmonte.flashChat',
  );
}
